language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

before_deploy:
  - npm run prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
